[application]
name = "another_pgp_tool"

[bundle]
identifier = "com.hahihula.another_pgp_tool"
publisher = "Hahihula"
icon = [
    "icons/icon.png", # Linux
    "icons/icon.ico", # Windows
    "icons/icon.icns"  # macOS
]
[web.app]

# HTML title tag content
title = "another_pgp_tool"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
