[application]
name = "another_pgp_tool"

[bundle]
identifier = "com.hahihula"
publisher = "Hahihula"
icon = ["assets/icon.png"]

[web.app]

# HTML title tag content
title = "another_pgp_tool"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
